name: Go Run Main

on:
  push:
    branches:
      - main

jobs:
  run-main:
    name: Run main.go
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Run main.go in backend directory
      run: |
        cd backend
        go run main.go

    - name: Wait for the server to start
      run: sleep 10  # Adjust the sleep time as needed

    - name: Check web service output
      run: |
        curl http://localhost:10000/

